package tr.edu.ku.devnull.needforspear.Model.Obstacle;

import tr.edu.ku.devnull.needforspear.Model.GameData.Constants;
import tr.edu.ku.devnull.needforspear.Model.GameData.GameMap;
import tr.edu.ku.devnull.needforspear.Model.GameData.Location;
import tr.edu.ku.devnull.needforspear.Model.GameData.Size;

/**
 * HollowPurpleObstacle is a class that one of the obstacle type which will be generated by the Ymir.
 */
public class HollowPurpleObstacle extends Obstacle{

    /**
     * Constructor of the HollowPurpleObstacle.
     *
     * @param gameMap Map to be placed on.
     * @param speed Speed of the obstacle.
     * @param location Location of the obstacle.
     */
    public HollowPurpleObstacle(GameMap gameMap, Double speed, Location location) {
        this.obstacleType = Constants.ObstacleNameConstants.HOLLOW_PURPLE_OBSTACLE;
        this.gameMap = gameMap;
        this.health = Constants.UIConstants.OBSTACLE_SIMPLE_HIT_HEALTH;
        this.speed = speed;
        this.size = new Size((int) ((Constants.UIConstants.INITIAL_SCREEN_WIDTH * Constants.ProportionConstants.RATIO_OF_NOBLE_PHANTASM) / Constants.UIConstants.OBSTACLE_SIZE_DIVISION_CONSTANT), Constants.ProportionConstants.HEIGHT_OF_THE_OBSTACLE);
        this.location = location;
        this.color = Constants.UIConstants.PURPLE_COLOR_STRING;
    }
}
